[package]
name = "stm32f3-pg"
version = "0.1.0"
edition = "2024"

[dependencies]
critical-section = { version = "1.2.0", features = [ "restore-state-u32" ] }
macros = { path = "../macros" }
rtt-target = "0.6.1"
utils = { path = "../utils" }

[[bin]]
name = "stm32f3-pg"
test = false
bench = false
