[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F303VCTx"
rustflags = [
  "-C", "linker=rust-lld",
  "-C", "link-arg=-Tmemory.x",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
test-arm = "test --target aarch64-unknown-linux-gnu"
test-win = "test --target x86_64-pc-windows-msvc"
debug-gdb = "run -- --runner probe-rs gdb"
